import type { Metadata } from "next";
import "./global.css";
import globalFonts from "@/config/global-font";
import { colorThemeClass } from "@/theme/color-theme.css";
import { typoThemeClass } from "@/theme/typo-theme.css";
import { sizeThemeClass } from "@/theme/size-theme.css";
import Header from "@/components/base/molecule/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ko"
      className={`${globalFonts} ${typoThemeClass} ${colorThemeClass} ${sizeThemeClass}`}
    >
      <body>
        <Header/>
        {children}
      </body>
    </html>
  );
}
